version: "3.7"
services:
  caesar:
    build:
      context: caesar/
      target: ${ENV:-production}
    image: caesar:${ENV:-latest}
  blackbox:
    build:
      context: blackbox/
      target: ${ENV:-production}
    image: blackbox:${ENV:-latest}
    environment:
      - APP_ENV=${ENV:-production}
      - CAESAR_ENDPOINT=tcp://caesar:50000
      - BULLSHIT_ENDPOINT=$BULLSHIT_ENDPOINT
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - 3001:80
  web:
    build:
      context: web/
      target: ${ENV:-production}
      args:
        - BLACKBOX_API_ENDPOINT=${BLACKBOX_PUBLIC_ENDPOINT:-/api}
    image: web:${ENV:-latest}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
