version: "3.7"
services:
  caesar:
  blackbox:
    ports:
      - 3001:80
    volumes:
      - ./blackbox:/var/www/html
  web:
    build:
      args:
        - BLACKBOX_API_ENDPOINT=${BLACKBOX_PUBLIC_ENDPOINT:-http://localhost:3001}
    volumes:
      - ./web:/home/node/app
    ports:
      - 3000:80
